version: 2.1

jobs:

  ready:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  format:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn prettier:list

  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  regression:
    docker:
      - image: circleci/node:10.13-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: mkdir -p $(dirname $GOOGLE_APPLICATION_CREDENTIALS)
      - run: echo $ENCODED_GOOGLE_APPLICATION_CREDENTIALS | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
      - run: yarn screenshot
      - run: yarn regression

  deploy-storybook:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn storybook:build
      - run: |
          cd storybook-static
          git init
          git config user.name "GH Pages Bot"
          git config user.email "gh-pages@github.com"
          git add .
          git commit --allow-empty -m "Deploy Storybook to GitHub Pages [ci skip]"
          git push -fq https://${GH_TOKEN}@github.com/minodisk/glaph.git master:gh-pages

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - ready
      - lint:
          requires:
            - ready
      - format:
          requires:
            - ready
      - test:
          requires:
          - ready
      - build:
          requires:
            - ready
      - regression:
          requires:
            - ready
      - deploy-storybook:
          requires:
            - ready
          filters:
            branches:
              only: master
